version: '3'
include:
  - "./server/docker-compose.yaml"

services:
  server:
    image: 'nginx:alpine'
    ports:
      - '8080:80'
    volumes:
      - './server/config/nginx.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - node_app
  web_app:
    image: node:latest
    container_name: web_app
    working_dir: /web_app
    volumes:
      - ./client_web:/web_app
    command: sh -c "yarn install && yarn build"
  client_web:
    image: 'nginx:alpine'
    ports:
      - '8081:80'
    volumes:
      - './client_web/config/nginx.conf:/etc/nginx/conf.d/default.conf'
      - './client_web/build:/app'
    depends_on:
      - node_app
      - web_app

  # client_mobile:
  #   image: ubuntu:latest
  #   container_name: client_mobile
  #   working_dir: /client_mobile
  #   volumes:
  #     - ./client_mobile:/client_mobile
  #   command: sh -c "apt update &&  apt install -y openjdk-11-jdk && apt install -y android-sdk && apt install -y nodejs curl wget &&  curl -qL https://www.npmjs.com/install.sh | sh && npm install -g n && n latest && npm install -g yarn && yarn && yarn expo prebuild && cd android && ./gradlew assembleRelease"



volumes:
  shared: